version: '3.9'

services:
  # consumer
  consumer: 
    build: ./consumer/
    hostname: consumer
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - CONSUMER_PORT=${CONSUMER_PORT}
    command: python consumer.py 
    volumes:
      - ./consumer/code:/app
    ports:
      - "${CONSUMER_PORT}:${CONSUMER_PORT}"
  api:
    build: ./api/
    hostname: ${API_HOST}
    environment:
      - API_PORT=${API_PORT}
      - DB_NAME=${DB_NAME}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - DB_HOST=${DB_HOST}
      - PG_PORT=${PG_PORT}
    command: python api.py
    volumes:
      - ./api/code:/app
    ports:
      - "${API_PORT}:${API_PORT}"
  db:
    image: postgres:latest
    hostname: ${DB_HOST}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "${PG_PORT}:${PG_PORT}"
  db_admin:
    image: dpage/pgadmin4
    hostname: dba
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_NAME}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PG_ADMIN_PORT}:${PG_ADMIN_PORT}"
volumes:
  data:
  pgadmin: