CREATE TABLE IF NOT EXISTS Meals (
    MealId SERIAL PRIMARY KEY
    ,MealName TEXT NOT NULL
    ,MealPrice REAL NOT NULL
);

INSERT INTO Meals(MealName, MealPrice) VALUES ('AVOCADO JHALMURI', 10.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('SPECIAL SAMOSA', 9.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('TANDOORI VEGETABLE', 20.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('ACHARI CHICKEN TIKKA', 21.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('TOMATO AND FENNEL SOUP', 10.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('MULLIGATAWANY SOUP', 10.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('BOMBAY FISH MASALA', 22.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('YELLOW DAL TARKA', 19.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('KADHAI BHINDI', 20.00);
INSERT INTO Meals(MealName, MealPrice) VALUES ('GARDEN PIZZA', 23.00);
INSERT INTO Meals(MealName, MealPrice) VALUES ('PEPPERONI PIZZA', 25.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('GARLIC BREAD', 8.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('CALZONE', 15.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('PANINI', 15.99);
INSERT INTO Meals(MealName, MealPrice) VALUES ('SALAD', 5.99);